<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="0" hostname="EPINHYDW0313" name="com.epam.week3.rest_assured_feedback_api_testing.FeedBackAPIGETRequestTest" tests="12" failures="2" timestamp="21 Dec 2018 06:50:13 GMT" time="1.745" errors="0">
  <testcase name="statusCodeByIdTest" time="1.196" classname="com.epam.week3.rest_assured_feedback_api_testing.FeedBackAPIGETRequestTest"/>
  <testcase name="responseBodyByIdTest" time="0.002" classname="com.epam.week3.rest_assured_feedback_api_testing.FeedBackAPIGETRequestTest"/>
  <testcase name="badStatusCodeByIdTest" time="0.001" classname="com.epam.week3.rest_assured_feedback_api_testing.FeedBackAPIGETRequestTest"/>
  <testcase name="statusCodeFromAndToTest" time="0.302" classname="com.epam.week3.rest_assured_feedback_api_testing.FeedBackAPIGETRequestTest"/>
  <testcase name="responseBodyFromAndToTest" time="0.004" classname="com.epam.week3.rest_assured_feedback_api_testing.FeedBackAPIGETRequestTest"/>
  <testcase name="badStatusCodeByFromAndToTest" time="0.003" classname="com.epam.week3.rest_assured_feedback_api_testing.FeedBackAPIGETRequestTest"/>
  <testcase name="statusCodeFromUserTest" time="0.157" classname="com.epam.week3.rest_assured_feedback_api_testing.FeedBackAPIGETRequestTest"/>
  <testcase name="responseBodyFromUserTest" time="0.005" classname="com.epam.week3.rest_assured_feedback_api_testing.FeedBackAPIGETRequestTest">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertTrue(Assert.java:44)
at org.testng.Assert.assertTrue(Assert.java:54)
at com.epam.week3.rest_assured_feedback_api_testing.FeedBackAPIGETRequestTest.responseBodyFromUserTest(FeedBackAPIGETRequestTest.java:129)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- responseBodyFromUserTest -->
  <testcase name="badStatusCodeByFromUserTest" time="0.001" classname="com.epam.week3.rest_assured_feedback_api_testing.FeedBackAPIGETRequestTest"/>
  <testcase name="statusCodeToUserTest" time="0.073" classname="com.epam.week3.rest_assured_feedback_api_testing.FeedBackAPIGETRequestTest"/>
  <testcase name="responseBodyToUserTest" time="0.001" classname="com.epam.week3.rest_assured_feedback_api_testing.FeedBackAPIGETRequestTest">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertTrue(Assert.java:44)
at org.testng.Assert.assertTrue(Assert.java:54)
at com.epam.week3.rest_assured_feedback_api_testing.FeedBackAPIGETRequestTest.responseBodyToUserTest(FeedBackAPIGETRequestTest.java:146)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- responseBodyToUserTest -->
  <testcase name="badStatusCodeByToUserTest" time="0.000" classname="com.epam.week3.rest_assured_feedback_api_testing.FeedBackAPIGETRequestTest"/>
</testsuite> <!-- com.epam.week3.rest_assured_feedback_api_testing.FeedBackAPIGETRequestTest -->
